### ISSUE TITLE
Example story board not work

### ISSUE THREAD

**Issue by sazidIqabal** [uptechteam/AirBar#2]
there is no way to use this library? or no proper description how it can be used..... also no such way to see the view

**Comment by romanfurman6** [comment]
@sazidIqabal hey, check it [https://blog.uptech.team/how-to-implement-expandable-menu-on-ios-like-in-airbnb-3d2bdd97b049](url). It's can help you ;)

**Comment by sazidIqabal** [comment]
now got it, thank you so much
